/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import common.ControllerInterface;

/**
 *
 * @author disi
 */
public class ControlPanel extends javax.swing.JPanel {

    ControllerInterface ctl;
            
    /**
     * Creates new form Control
     */
        
    public ControlPanel() {
        initComponents();
    }
    
    public ControlPanel(ControllerInterface ctl_param) {
        initComponents();
        ctl= ctl_param;
    }

    public void setController(ControllerInterface ctl_param){
        ctl= ctl_param;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 200));
        setLayout(new java.awt.GridLayout(1, 0));

        start.setText("Start Regulating");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        add(start);

        stop.setText("Stop Regulating");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        add(stop);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        try{
            ctl.startControlling();
        }
        catch (InterruptedException ie){
            
        }
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        try{
            ctl.stopControlling();
        }
        catch (InterruptedException ie){
            
        }
    }//GEN-LAST:event_stopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
