/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import common.ControllerInterface;
import controller_01.Controller_01;
import controller_11.Controller_11;
import controller_11_manual_test.Controller_11_Manual_Test;
import controller_11_manual_test.ManualTest;
import java.awt.BorderLayout;

/**
 *
 * @author segovia
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    
    ControllerInterface ctl;
    PanelCTL ctl01;
    
    public PrincipalFrame() {
        initComponents();
        ctl = null;
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initialPanel = new javax.swing.JPanel();
        button_ctl_01 = new javax.swing.JButton();
        button_ctl_11 = new javax.swing.JButton();
        button_ctl_12 = new javax.swing.JButton();
        button_ctl_22 = new javax.swing.JButton();
        button_ctl_23 = new javax.swing.JButton();
        button_ctl_24 = new javax.swing.JButton();
        button_ctl_34 = new javax.swing.JButton();
        button_ctl_44 = new javax.swing.JButton();
        button_ctl_13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        initialPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        button_ctl_01.setText("Controller (0,1)");
        button_ctl_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_01ActionPerformed(evt);
            }
        });

        button_ctl_11.setText("Controller (1,1)");
        button_ctl_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_11ActionPerformed(evt);
            }
        });

        button_ctl_12.setText("Controller (1,2)");
        button_ctl_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_12ActionPerformed(evt);
            }
        });

        button_ctl_22.setText("Controller (2,2)");
        button_ctl_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_22ActionPerformed(evt);
            }
        });

        button_ctl_23.setText("Controller (2,3)");
        button_ctl_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_23ActionPerformed(evt);
            }
        });

        button_ctl_24.setText("Controller (2,4)");
        button_ctl_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_24ActionPerformed(evt);
            }
        });

        button_ctl_34.setText("Controller (3,4)");
        button_ctl_34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_34ActionPerformed(evt);
            }
        });

        button_ctl_44.setText("Controller (4,4)");
        button_ctl_44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_44ActionPerformed(evt);
            }
        });

        button_ctl_13.setText("Manual Test ");
        button_ctl_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ctl_13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout initialPanelLayout = new javax.swing.GroupLayout(initialPanel);
        initialPanel.setLayout(initialPanelLayout);
        initialPanelLayout.setHorizontalGroup(
            initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialPanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_ctl_44)
                    .addComponent(button_ctl_34)
                    .addComponent(button_ctl_24)
                    .addComponent(button_ctl_23)
                    .addComponent(button_ctl_22)
                    .addComponent(button_ctl_12)
                    .addGroup(initialPanelLayout.createSequentialGroup()
                        .addComponent(button_ctl_11)
                        .addGap(30, 30, 30)
                        .addComponent(button_ctl_13))
                    .addComponent(button_ctl_01))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        initialPanelLayout.setVerticalGroup(
            initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(button_ctl_01)
                .addGap(18, 18, 18)
                .addGroup(initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_ctl_11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ctl_13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_ctl_12)
                .addGap(18, 18, 18)
                .addComponent(button_ctl_22)
                .addGap(18, 18, 18)
                .addComponent(button_ctl_23)
                .addGap(18, 18, 18)
                .addComponent(button_ctl_24)
                .addGap(18, 18, 18)
                .addComponent(button_ctl_34)
                .addGap(18, 18, 18)
                .addComponent(button_ctl_44)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initialPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ctl_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_01ActionPerformed
                
        ctl= new Controller_01();              
        
        //change pannel
        this.getContentPane().remove(initialPanel);         
        this.setLayout(new BorderLayout());        
        PanelCTL panel_ctl_01 = new PanelCTL((Controller_01) ctl);        
        this.add(panel_ctl_01);            
        this.pack();
        this.setVisible(true);
        
    }//GEN-LAST:event_button_ctl_01ActionPerformed

    private void button_ctl_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_11ActionPerformed
        
        ctl= new Controller_11();          
        
        //change pannel
        this.getContentPane().remove(initialPanel);         
        this.setLayout(new BorderLayout());        
        PanelCTL panel_ctl_11 = new PanelCTL((Controller_11) ctl);        
        this.add(panel_ctl_11);            
        this.pack();
        this.setVisible(true);

    }//GEN-LAST:event_button_ctl_11ActionPerformed

    private void button_ctl_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ctl_12ActionPerformed

    private void button_ctl_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ctl_22ActionPerformed

    private void button_ctl_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ctl_23ActionPerformed

    private void button_ctl_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ctl_24ActionPerformed

    private void button_ctl_34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ctl_34ActionPerformed

    private void button_ctl_44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ctl_44ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        if (ctl != null){ 
            ctl.sendCloseConnection(0);
            ctl.sendCloseConnection(1);
            ctl.sendCloseConnection(-1);
        }
    }//GEN-LAST:event_formWindowClosing

    private void button_ctl_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ctl_13ActionPerformed
        
        //change pannel
        this.getContentPane().remove(initialPanel);         
        this.setLayout(new BorderLayout());        
        ManualTest panel_ctl_11 = new ManualTest();        
        this.add(panel_ctl_11);            
        this.pack();
        this.setVisible(true);
    }//GEN-LAST:event_button_ctl_13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ctl_01;
    private javax.swing.JButton button_ctl_11;
    private javax.swing.JButton button_ctl_12;
    private javax.swing.JButton button_ctl_13;
    private javax.swing.JButton button_ctl_22;
    private javax.swing.JButton button_ctl_23;
    private javax.swing.JButton button_ctl_24;
    private javax.swing.JButton button_ctl_34;
    private javax.swing.JButton button_ctl_44;
    private javax.swing.JPanel initialPanel;
    // End of variables declaration//GEN-END:variables

        
}
